language: generic

sudo: required

services:
  - docker

before_script:
- docker build -t stm32f7-discovery .

script:
- docker run stm32f7-discovery sh -c "
    set -e;
    pwd; ls;
    echo `pwd`;
    RUST_TARGET_PATH=`pwd`;
    xargo build;
    cd blinking_led;
    RUST_TARGET_PATH=`pwd`;
    xargo update && xargo build
  "
