language: rust
rust: nightly
cache: cargo
dist: trusty

addons:
  apt:
    sources:
    - llvm-toolchain-trusty
    packages:
    - lld-5.0

before_script:
- rustup component add rust-src
- cd ..
- (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
- (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
- cargo install-update -a
- cd stm32f7-discovery

script:
- xargo build
