[package]
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
name = "novemb-rs-stm32f7"
version = "0.1.0"

[dependencies]
compiler-builtins-snapshot = "0.0.20161008+c56faf22abb39724008148d58f12bcd43b6d236b"
cortex-m = "0.1.4"
r0 = "0.1.0"
rlibc = "1.0.0"
volatile = "0.2.0"

[dependencies.svd_board]
version = "0.2.1"
features = ["stm32f7"]

[[bin]]
name = "novemb-rs-stm32f7"
doc = false
