[package]
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
name = "stm32f7_discovery"
version = "0.1.0"
license = "MIT/Apache-2.0"

[[bin]]
doc = false
name = "stm32f7_discovery"

[dependencies]
bit_field = "0.7.0"
byteorder = { version = "1.0.0", default-features = false }
cortex-m = "0.1.4"
r0 = "0.1.0"
spin = "0.4.5"
volatile = "0.2.1"
rusttype = {git = "https://github.com/phil-opp/rusttype.git", branch = "no_std"}
alloc-cortex-m = {git = "https://github.com/embed-rs/alloc-cortex-m.git", branch = "master" }

[dependencies.arrayvec]
default-features = false
version = "0.3.20"

[dependencies.embedded_stm32f7]
git = "https://github.com/embed-rs/embedded_stm32f7.git"

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp.git"
default-features = false
features = ["alloc", "socket-raw", "socket-udp", "socket-tcp", "socket-icmp", "proto-ipv4"]

[profile]

[profile.release]
lto = true
debug = true
